# -*- coding: utf-8 -*-
"""INTERNSHIP TASK 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1-eXi2l71ap8BrQIcSA6BIjTmaWYw8T
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset("iris")

iris.head()

print("Shape of dataset:", iris.shape)

print("Column names:", iris.columns)

iris.head()

iris.info()

iris.describe()

sns.scatterplot(x="sepal_length", y="petal_length", hue="species", data=iris)

plt.title("Sepal Length vs Petal Length")
plt.show()

iris.hist(figsize=(8,6))

plt.suptitle("Distribution of Iris Features")
plt.show()

sns.boxplot(data=iris)

plt.title("Boxplot of Iris Dataset Features")
plt.show()

